run:
  timeout: 3m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 100
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/CloudNativeAI/modctl)

issues:
  new: true
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
  exclude-dirs:
    - test/mocks

linters:
  disable-all: true
  enable:
    - gci
    - gofmt
    - golint
    - misspell
    - govet
    - goconst
    - deadcode
    - gocyclo
    - staticcheck
    - errcheck

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
