name: Lint

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version-file: go.mod
          cache: false

      - name: Golangci lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8
        with:
          version: v1.54
          args: --verbose
